import { Document, Page, Text, View, StyleSheet, Font, Image } from '@react-pdf/renderer';

// Register a nice serif font if possible, or stick to defaults for now
// Font.register({ family: 'Helvetica', ... });

const styles = StyleSheet.create({
  page: {
    padding: 60,
    backgroundColor: '#fff',
    fontFamily: 'Helvetica',
  },
  title: {
    fontSize: 24,
    textAlign: 'center',
    marginBottom: 10,
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  metadata: {
    fontSize: 10,
    textAlign: 'center',
    color: '#666',
    marginBottom: 30,
    textTransform: 'uppercase',
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    marginTop: 20,
    marginBottom: 10,
    textTransform: 'uppercase',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    paddingBottom: 2,
  },
  abstractBox: {
    backgroundColor: '#f9f9f9',
    padding: 15,
    borderLeftWidth: 3,
    borderLeftColor: '#ccc',
    marginBottom: 20,
  },
  abstractText: {
    fontSize: 10,
    fontStyle: 'italic',
    lineHeight: 1.5,
    textAlign: 'justify',
  },
  bodyText: {
    fontSize: 11,
    lineHeight: 1.6,
    textAlign: 'justify',
    marginBottom: 10,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 0,
    right: 0,
    textAlign: 'center',
    fontSize: 8,
    color: '#aaa',
    textTransform: 'uppercase',
  },
  image: {
    marginVertical: 15,
    marginHorizontal: 'auto',
    borderRadius: 5,
    maxWidth: '100%',
  },
});

interface PaperJson {
  metadata: {
    title: string;
    author: string;
    date: string;
    institution: string;
  };
  sections: {
    id: string;
    type: string;
    title: string;
    content: string;
  }[];
}

export default function InstantPdfDocument({ data }: { data: PaperJson }) {
  if (!data || !data.metadata) return null;

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        {/* Header */}
        <View>
          <Text style={styles.title}>{data.metadata.title}</Text>
          <Text style={styles.metadata}>
            {data.metadata.author} {'\n'}
            {data.metadata.institution} • {data.metadata.date}
          </Text>
        </View>

        {/* Content */}
        {data.sections.map((section) => (
          <View key={section.id}>
            {section.type === 'abstract' ? (
              <View style={styles.abstractBox}>
                <Text style={{ fontWeight: 'bold', fontSize: 11, marginBottom: 5 }}>Abstract</Text>
                <Text style={styles.abstractText}>{section.content}</Text>
              </View>
            ) : section.type === 'image' ? (
              <View>
                <Text style={styles.sectionTitle}>{section.title}</Text>
                {section.content && section.content.startsWith('http') ? (
                  <Image src={section.content} style={styles.image} />
                ) : (
                  <Text style={[styles.bodyText, { color: 'red' }]}>Invalid Image URL: {section.content}</Text>
                )}
              </View>
            ) : (
              <>
                <Text style={styles.sectionTitle}>{section.title}</Text>
                <Text style={styles.bodyText}>{section.content}</Text>
              </>
            )}
          </View>
        ))}

        <Text style={styles.footer} render={({ pageNumber, totalPages }) => (
          `Page ${pageNumber} of ${totalPages} • Generated by ARS Lab`
        )} fixed />
      </Page>
    </Document>
  );
}
